---
- hosts: compute
  strategy: free
  become: true
  remote_user: cc
  tasks:
    - name: Copy hosts file
      copy:
        src: ../src/hosts
        dest: /etc/hosts
        owner: root
        group: root
        mode: '0644'

    - name: Copy ssh config
      copy:
        src: ../src/ssh_config
        dest: /etc/ssh/ssh_config
        owner: root
        group: root
        mode: '0644'

#    - name: Install openMPI
#      yum:
#        name: openmpi
#        state: latest
#
#    - name: Install llvm
#      yum:
#        name: llvm
#        state: latest
#
#    - name: Install OpenBLAS
#      yum:
#        name: openblas
#        state: latest

    - name: Mount nfs fileshare
      shell: sudo mount head-node:/home /home
