---
- hosts: head
  become: true
  remote_user: cc
  tasks:
    - name: Copy exports file
      copy:
        src: ../src/exports
        dest: /etc/exports
        owner: root
        group: root
        mode: '0644'

    - name: Copy hosts file
      copy:
        src: ../src/hosts
        dest: /etc/hosts
        owner: root
        group: root
        mode: '0644'